### ISSUE TITLE
Plugin use not the last version of JSHint

### ISSUE THREAD

**Issue by anna-bildyug** [eriwen/gradle-js-plugin#145] opened 2017-03-14 07:05 UTC
Plugin uses version 2.4.3 while the last version is 2.9.4
Due to the issue a lot of not actual warnings failed during verification.
Please update version of JSHint

**Comment by eriwen** [comment] 2017-09-18 05:08
@anna-bildyug I'm afraid that jshint has been broken on rhino for quite some time due to https://github.com/jshint/jshint/issues/2308. 

It would be preferable to use an `ExecTask` or the `gradle-node-plugin` to achieve this if you need it.

**Comment by eriwen** [comment] 2017-09-18 05:14
I'm going to close this as a duplicate of #113

**Closed by eriwen** 2017-09-18 05:14 UTC
